spring:
  application:
    name: project

  datasource:
    url: jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/ihm_db?useSSL=true&requireSSL=true&serverTimezone=-05:00&useUnicode=true&characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
